# <center>  <div style="background-color:#9E1A1A;color:white;padding:5%"> <font size="6"> Mini-projet 1 : L'IA pour les mesures des champs électromagnétiques <br> <br> <br>  <center> Hazem Aich  <font size="4"> <br> 2 DNI 1 </center> </div> 

#   ` Test du modèle avec des  données originales`

In [4]:
%matplotlib inline
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('ANFR_Herault_Mesures_originales_pour_jpynb1.csv',delimiter=';')
df.head()

Numéro de mesure  Longitude  Latitude  \
0               175    3.91611  43.58528   
1               180    4.04194  43.64694   
2               543    3.03167  43.36028   
3               545    3.03278  43.36167   
4               850    3.56444  43.64583   

                                    Position  Insee  \
0  03° 54' 58.00'' Est, 43° 35' 07.00'' Nord  34129   
1  04° 02' 31.00'' Est, 43° 38' 49.00'' Nord  34176   
2  03° 01' 54.00'' Est, 43° 21' 37.00'' Nord  34225   
3  03° 01' 58.00'' Est, 43° 21' 42.00'' Nord  34225   
4  03° 33' 52.00'' Est, 43° 38' 45.00'' Nord  34114   

                               Adresse                 Complément  \
0                           Mas de Gau                        NaN   
1  5539 Rue Lou Claou de la Oulivettas                        NaN   
2                 Chemin de Montfaucon  résidence de  Mme SOUTADE   
3                   Chemin de Quarante  résidence de  M. GONZALEZ   
4           480 Chemin de Pioch Courbi      Chez Mme et M. GALOIS   

   Code postal       Commune Date de mesure Mesure réalisée  \
0        34970        LATTES     06/12/2001    En extérieur   
1        34130      MUDAISON     06/12/2001    En extérieur   
2        34620  PUISSERGUIER     23/05/2002    En extérieur   
3        34620  PUISSERGUIER     23/05/2002    En extérieur   
4        34150        GIGNAC     10/10/2002    En extérieur   

              Rapport Conformité de la mesure  Niveau global  \
0  FicheMesure175.pdf                     Oui           0.00   
1  FicheMesure180.pdf                     Oui           0.00   
2  FicheMesure543.pdf                     Oui           0.54   
3  FicheMesure545.pdf                     Oui           0.20   
4  FicheMesure850.pdf                     Oui           0.53   

    Type d'environnement Laboratoire  
0                 Divers     SATELIT  
1                 Divers     SATELIT  
2                 Divers       APAVE  
3                 Divers       APAVE  
4  Rue / Route / Parking       APAVE

In [5]:
df.rename(columns={'Niveau global': 'Niveau_global'}, inplace=True)

In [6]:
df=df.assign(target=1)
print(df)

     Numéro de mesure  Longitude  Latitude  \
0                 175    3.91611  43.58528   
1                 180    4.04194  43.64694   
2                 543    3.03167  43.36028   
3                 545    3.03278  43.36167   
4                 850    3.56444  43.64583   
..                ...        ...       ...   
907            159667    3.87667  43.59809   
908            160107    3.86363  43.60516   
909            160146    3.22983  43.36141   
910            160274    3.86367  43.60505   
911            160278    3.48046  43.28074   

                                      Position  Insee  \
0    03° 54' 58.00'' Est, 43° 35' 07.00'' Nord  34129   
1    04° 02' 31.00'' Est, 43° 38' 49.00'' Nord  34176   
2    03° 01' 54.00'' Est, 43° 21' 37.00'' Nord  34225   
3    03° 01' 58.00'' Est, 43° 21' 42.00'' Nord  34225   
4    03° 33' 52.00'' Est, 43° 38' 45.00'' Nord  34114   
..                                         ...    ...   
907  03° 52' 36.02'' Est, 43° 35' 53.11'' Nord  

In [7]:
df.columns

Index(['Numéro de mesure', 'Longitude', 'Latitude', 'Position', 'Insee',
       'Adresse', 'Complément', 'Code postal', 'Commune', 'Date de mesure',
       'Mesure réalisée', 'Rapport', 'Conformité de la mesure',
       'Niveau_global', 'Type d'environnement', 'Laboratoire', 'target'],
      dtype='object')

## `Fonction Target` : 

In [8]:
def target():
    for t in range(0,len(df)):
        if df['Niveau_global'][t] > 6 :
            df['target'][t] = 0
            print(df['Niveau_global'][t]) 

In [9]:
target()

9.63
8.44
8.03
9.06
9.05
6.65
15.66
25.39
10.33
9.1
6.98
21.03
10.57
8.52


<ipython-input-8-e39c486678de>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['target'][t] = 0


In [10]:
pd.crosstab(df.target, "freq")

col_0   freq
target      
0         14
1        898

In [11]:
df.head()

Numéro de mesure  Longitude  Latitude  \
0               175    3.91611  43.58528   
1               180    4.04194  43.64694   
2               543    3.03167  43.36028   
3               545    3.03278  43.36167   
4               850    3.56444  43.64583   

                                    Position  Insee  \
0  03° 54' 58.00'' Est, 43° 35' 07.00'' Nord  34129   
1  04° 02' 31.00'' Est, 43° 38' 49.00'' Nord  34176   
2  03° 01' 54.00'' Est, 43° 21' 37.00'' Nord  34225   
3  03° 01' 58.00'' Est, 43° 21' 42.00'' Nord  34225   
4  03° 33' 52.00'' Est, 43° 38' 45.00'' Nord  34114   

                               Adresse                 Complément  \
0                           Mas de Gau                        NaN   
1  5539 Rue Lou Claou de la Oulivettas                        NaN   
2                 Chemin de Montfaucon  résidence de  Mme SOUTADE   
3                   Chemin de Quarante  résidence de  M. GONZALEZ   
4           480 Chemin de Pioch Courbi      Chez Mme et M. GALOIS   

   Code postal       Commune Date de mesure Mesure réalisée  \
0        34970        LATTES     06/12/2001    En extérieur   
1        34130      MUDAISON     06/12/2001    En extérieur   
2        34620  PUISSERGUIER     23/05/2002    En extérieur   
3        34620  PUISSERGUIER     23/05/2002    En extérieur   
4        34150        GIGNAC     10/10/2002    En extérieur   

              Rapport Conformité de la mesure  Niveau_global  \
0  FicheMesure175.pdf                     Oui           0.00   
1  FicheMesure180.pdf                     Oui           0.00   
2  FicheMesure543.pdf                     Oui           0.54   
3  FicheMesure545.pdf                     Oui           0.20   
4  FicheMesure850.pdf                     Oui           0.53   

    Type d'environnement Laboratoire  target  
0                 Divers     SATELIT       1  
1                 Divers     SATELIT       1  
2                 Divers       APAVE       1  
3                 Divers       APAVE       1  
4  Rue / Route / Parking       APAVE       1

In [12]:
X=df[['Numéro de mesure','Niveau_global']].to_numpy()
print(X)
y=df['target'].to_numpy()
print(y)

[[1.75000e+02 0.00000e+00]
 [1.80000e+02 0.00000e+00]
 [5.43000e+02 5.40000e-01]
 ...
 [1.60146e+05 3.27000e+00]
 [1.60274e+05 9.20000e-01]
 [1.60278e+05 1.29000e+00]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [14]:
from sklearn.linear_model import LogisticRegression 
#Create a l.Reg Classifier
logreg1 = LogisticRegression()
#Train the model using the training sets
logreg1.fit(X_train, y_train)
y_pred=logreg1.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[  3   0]
 [  0 271]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00       271

    accuracy                           1.00       274
   macro avg       1.00      1.00      1.00       274
weighted avg       1.00      1.00      1.00       274

1.0


#   ` Test du modèle avec des nouvelles données `




In [16]:
df1=pd.read_csv('nouvelle.csv',delimiter=';')
df1.head()

Numéro de mesure  Longitude  Latitude  \
0                 1    3.91611  43.58528   
1                 2    4.04194  43.64694   
2                 3    3.03167  43.36028   
3                 4    3.03278  43.36167   
4                 5    3.56444  43.64583   

                                    Position  Insee  \
0  03° 54' 58.00'' Est, 43° 35' 07.00'' Nord  34129   
1  04° 02' 31.00'' Est, 43° 38' 49.00'' Nord  34176   
2  03° 01' 54.00'' Est, 43° 21' 37.00'' Nord  34225   
3  03° 01' 58.00'' Est, 43° 21' 42.00'' Nord  34225   
4  03° 33' 52.00'' Est, 43° 38' 45.00'' Nord  34114   

                               Adresse                 Complément  \
0                           Mas de Gau                        NaN   
1  5539 Rue Lou Claou de la Oulivettas                        NaN   
2                 Chemin de Montfaucon  résidence de  Mme SOUTADE   
3                   Chemin de Quarante  résidence de  M. GONZALEZ   
4           480 Chemin de Pioch Courbi      Chez Mme et M. GALOIS   

   Code postal       Commune Date de mesure  Mesure réalisée  \
0        34970        LATTES     06/12/2001              NaN   
1        34130      MUDAISON     06/12/2001              NaN   
2        34620  PUISSERGUIER     23/05/2002              NaN   
3        34620  PUISSERGUIER     23/05/2002              NaN   
4        34150        GIGNAC     10/10/2002              NaN   

              Rapport Conformité de la mesure  Niveau global  \
0  FicheMesure175.pdf                     Oui           4.01   
1  FicheMesure180.pdf                     Oui          20.10   
2  FicheMesure543.pdf                     Oui           3.90   
3  FicheMesure545.pdf                     Oui           2.30   
4  FicheMesure850.pdf                     Oui           5.90   

    Type d'environnement Laboratoire  
0                 Divers     SATELIT  
1                 Divers     SATELIT  
2                 Divers       APAVE  
3                 Divers       APAVE  
4  Rue / Route / Parking       APAVE

In [17]:
df1.rename(columns={'Niveau global': 'Niveau_global'}, inplace=True)

In [18]:
df1=df1.assign(target1=1)
print(df1)

    Numéro de mesure  Longitude  Latitude  \
0                  1    3.91611  43.58528   
1                  2    4.04194  43.64694   
2                  3    3.03167  43.36028   
3                  4    3.03278  43.36167   
4                  5    3.56444  43.64583   
5                  6    3.56306  43.64806   
6                  7    3.56306  43.64694   
7                  8    3.91611  43.58500   
8                  9    3.91667  43.58667   
9                 10    3.87806  43.60556   
10                11    3.82389  43.63361   
11                12    3.94556  43.57028   
12                13    3.68583  43.40194   
13                14    3.37167  43.50944   
14                15    3.37889  43.50611   
15                16    3.83944  43.61694   
16                17    3.83944  43.61611   
17                18    3.86361  43.59278   
18                19    3.86500  43.59306   
19                20    3.60750  43.42583   
20                21    3.88083  43.61611   
21        

## `Fonction Target1` : 

In [19]:
def target1():
    for t in range(0,len(df1)):
        if df1['Niveau_global'][t] > 6 :
            df1['target1'][t] = 0
            print(df1['Niveau_global'][t]) 

In [20]:
target1()

20.1
10.02
6.5
7.1
6.2
6.9
6.7
25.0
7.02
9.2
10.7
6.1


<ipython-input-19-bbd9274d20b9>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['target1'][t] = 0


In [21]:
z=df1[['Numéro de mesure','Niveau_global']].to_numpy()
print(z)
a=df1['target1'].to_numpy()
print(a)

[[ 1.    4.01]
 [ 2.   20.1 ]
 [ 3.    3.9 ]
 [ 4.    2.3 ]
 [ 5.    5.9 ]
 [ 6.   10.02]
 [ 7.    6.5 ]
 [ 8.    7.1 ]
 [ 9.    4.06]
 [10.    6.2 ]
 [11.    6.9 ]
 [12.    5.5 ]
 [13.    5.6 ]
 [14.    6.7 ]
 [15.   25.  ]
 [16.    7.02]
 [17.    9.2 ]
 [18.    3.9 ]
 [19.   10.7 ]
 [20.    2.9 ]
 [21.    6.1 ]
 [22.    5.7 ]
 [23.    4.6 ]
 [24.    5.5 ]]
[1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 0 1 0 1 0 1 1 1]


In [22]:
y1_pred=logreg1.predict(z)
print(y1_pred)

[1 0 1 1 1 0 1 0 1 1 0 1 1 0 0 0 0 1 0 1 1 1 1 1]


In [23]:
pd.crosstab(df1.target1, "freq")

col_0    freq
target1      
0          12
1          12

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [25]:
from sklearn.linear_model import LogisticRegression 
#Create a l.Reg Classifier
logreg1 = LogisticRegression()
#Train the model using the training sets
logreg1.fit(X_train, y_train)
y_pred=logreg1.predict(X_test)

In [26]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(a,y1_pred))
print(classification_report(a,y1_pred))
print(accuracy_score(a,y1_pred))

[[ 9  3]
 [ 0 12]]
              precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.80      1.00      0.89        12

    accuracy                           0.88        24
   macro avg       0.90      0.88      0.87        24
weighted avg       0.90      0.88      0.87        24

0.875
